export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const FETCH_POSTS = "POST/FETCH_POSTS";
export const FETCH_POSTS_SUCCESS = "POST/FETCH_POSTS_SUCCESS";

// export const CREATE_POST = "POST/CREATE_POST";

export const USER_PROFILE = "USERS/PROFILE";
export const USER_PROFILE_SUCCESS = "USERS/PROFILE_SUCCESS";
