export const REGISTER_USER = "USERS/REGISTER_USER";
export const REGISTER_USER_SUCCESS = "USERS/REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "USERS/REGISTER_USER_ERROR";

export const LOGIN_USER = "USERS/LOGIN_USER";
export const LOGIN_USER_SUCCESS = "USERS/LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "USERS/LOGIN_USER_ERROR";

export const USER_PROFILE = "USERS/PROFILE";
export const USER_PROFILE_SUCCESS = "USERS/PROFILE_SUCCESS";

export const FETCH_POSTS = "POST/FETCH_POSTS";
export const FETCH_POSTS_SUCCESS = "POST/FETCH_POSTS_SUCCESS";
export const CREATE_POST = "POST/CREATE_POST";
export const CREATE_POST_SUCCESS = "POST/CREATE_POST_SUCCESS";
export const DELETE_POST = "POST/DELETE_POST";
export const DELETE_POST_SUCCESS = "POST/DELETE_POST_SUCCESS";

export const FETCH_SINGLE_POST = "POST/FETCH_SINGLE_POST";
export const FETCH_SINGLE_POST_SUCCESS = "POST/FETCH_SINGLE_POST_SUCCESS";

export const EDIT_POST = "POST/EDIT_POST";
export const EDIT_POST_SUCCESS = "POST/EDIT_POST_SUCCESS";

export const FETCH_COMMENTS = "COMMENT/FETCH_COMMENTS";
export const FETCH_COMMENTS_SUCCESS = "COMMENT/FETCH_COMMENTS_SUCCESS";
export const CREATE_COMMENT = "COMMENT/CREATE_COMMENT";
export const CREATE_COMMENT_SUCCESS = "COMMENT/CREATE_COMMENT_SUCCESS";
export const DELETE_COMMENT = "COMMENT/DELETE_COMMENT";
export const DELETE_COMMENT_SUCCESS = "COMMENT/DELETE_COMMENT_SUCCESS";
